#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     endstop,        sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     rightdrive1,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftdrive2,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rightdrive2,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftdrive1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     intakesweep,   tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    hook1,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    hook2,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    door,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define MOTOR_STOP 0
#define MOTOR_HALF 50
#define MOTOR_MAX 100
#define RElEASE_OPEN 0
#define RELEASE_CLOSE 50

#define HOOK_DOWN_RIGHT 245
#define HOOK_UP_RIGHT 100

#define HOOK_DOWN_LEFT 51
#define HOOK_UP_LEFT 205

#define DOOR_CLOSE 0
#define DOOR_OPEN 125


void sweep(int power);
void manual_lift(int power);
void boxdoor (int position);

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
void hook(int position1, int position2)
{
	servoTarget[hook1] = position1;
	servoTarget[hook2] = position2;
}

void manual_lift(int power)
{
	motor[lift] = power;
	//motor[rightLift] = power;
}

void boxdoor(int position)
{
	servoTarget[door] = position;
}

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	servoTarget[hook1] = HOOK_UP_RIGHT;
	servoTarget[hook2] = HOOK_UP_LEFT;

	servoTarget[door] = DOOR_CLOSE;

  return;
}



/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////
  ////                                                   ////
  ////    Add your robot specific autonomous code here.  ////
  ////                                                   ////
  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////

  motor[leftdrive1] = -MOTOR_MAX;
  motor[rightdrive1] = -MOTOR_MAX;
  motor[leftdrive2] = -MOTOR_MAX;
  motor[rightdrive2] = -MOTOR_MAX;
  wait1Msec(700);
  motor[leftdrive1] = MOTOR_STOP;
  motor[rightdrive1] = MOTOR_STOP;
  motor[leftdrive2] = MOTOR_STOP;
  motor[rightdrive2] = MOTOR_STOP;

  hook(HOOK_DOWN_RIGHT, HOOK_DOWN_LEFT);

  manual_lift(MOTOR_MAX);
  wait1Msec(3000);

  boxdoor(DOOR_OPEN);
  wait1Msec(1500);
  boxdoor(DOOR_CLOSE);
  wait1Msec(1500);

  manual_lift(-MOTOR_MAX);
  wait1Msec(3000);

  motor[leftdrive1] = MOTOR_MAX;
  motor[rightdrive1] = MOTOR_MAX;
  motor[leftdrive2] = MOTOR_MAX;
  motor[rightdrive2] = MOTOR_MAX;
  wait1Msec(1500);
  motor[leftdrive1] = MOTOR_STOP;
  motor[rightdrive1] = MOTOR_STOP;
  motor[leftdrive2] = MOTOR_STOP;
  motor[rightdrive2] = MOTOR_STOP;

  motor[leftdrive1] = MOTOR_MAX;
  motor[rightdrive1] = MOTOR_HALF;
  motor[leftdrive2] = MOTOR_MAX;
  motor[rightdrive2] = MOTOR_HALF;
  wait1Msec(1500);
  motor[leftdrive1] = MOTOR_STOP;
  motor[rightdrive1] = MOTOR_STOP;
  motor[leftdrive2] = MOTOR_STOP;
  motor[rightdrive2] = MOTOR_STOP;

  motor[leftdrive1] = MOTOR_MAX;
  motor[rightdrive1] = MOTOR_MAX;
  motor[leftdrive2] = MOTOR_MAX;
  motor[rightdrive2] = MOTOR_MAX;
  wait1Msec(5200);
  motor[leftdrive1] = MOTOR_STOP;
  motor[rightdrive1] = MOTOR_STOP;
  motor[leftdrive2] = MOTOR_STOP;
  motor[rightdrive2] = MOTOR_STOP;

  motor[leftdrive1] = MOTOR_MAX;
  motor[rightdrive1] = -MOTOR_MAX;
  motor[leftdrive2] = MOTOR_MAX;
  motor[rightdrive2] = -MOTOR_MAX;
  wait1Msec(1200);
  motor[leftdrive1] = MOTOR_STOP;
  motor[rightdrive1] = MOTOR_STOP;
  motor[leftdrive2] = MOTOR_STOP;
  motor[rightdrive2] = MOTOR_STOP;

  while (true)
  {}
}
