#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     endstop,        sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     rightdrive1,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftdrive2,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rightdrive2,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftdrive1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     intakesweep,   tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    hook1,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    hook2,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    door,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define BTN_TRIG_LT 7
#define BTN_TRIG_RT 8
#define BTN_FACE_X 1
#define BTN_FACE_Y 4
#define BTN_FACE_A 2
#define BTN_FACE_B 3
#define BTN_BUMP_LB 5
#define BTN_BUMP_RB 6

#define BTN_SWEEP_IN  BTN_TRIG_LT
#define BTN_SWEEP_OUT BTN_TRIG_RT
#define BTN_HOOK_DOWN BTN_FACE_X
#define BTN_HOOK_UP   BTN_FACE_B
#define BTN_LIFT_UP BTN_FACE_Y
#define BTN_LIFT_DOWN BTN_FACE_A
#define BTN_DOOR_CLOSE BTN_BUMP_LB
#define BTN_DOOR_OPEN BTN_BUMP_RB

#define POV_UP 0
#define POV_DOWN 4
#define POV_LEFT 6
#define POV_RIGHT 2

#define MOTOR_STOP 0
#define MOTOR_HALF 50
#define MOTOR_MAX 100
#define HOOK_DOWN_RIGHT 245
#define HOOK_UP_RIGHT 100

#define HOOK_DOWN_LEFT 51
#define HOOK_UP_LEFT 205

#define DOOR_CLOSE 0
#define DOOR_OPEN 125

#define ENDSTOP_THRES 45

#define LIFT_BOTTOM 0
#define LIFT_MIDDLE 500
#define LIFT_TOP 1000

int joystick_threshold = 10;

int lift_target = 0;

int hook_up = 1;

int manual_lift_mode = 0;

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
void control ();
void drivetrain ();
void sweep(int power);
void manual_lift(int power);
void hook(int position1, int position2);
void doorslide();
void boxdoor(int position);

task Lift_Task();

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	servoTarget[hook1] = HOOK_UP_RIGHT;
	servoTarget[hook2] = HOOK_UP_LEFT;

	servoTarget[door] = DOOR_CLOSE;

  return;
}
void control ()
{
	getJoystickSettings(joystick);

	if(joy1Btn(BTN_SWEEP_IN))
	{
		sweep(MOTOR_MAX);
	}
	else if (joy1Btn(BTN_SWEEP_OUT))
	{
		sweep(-MOTOR_MAX);
	}
	else
	{
		sweep(MOTOR_STOP);
	}

	if (joy1Btn(BTN_HOOK_DOWN))
	{
		hook(HOOK_DOWN_RIGHT,HOOK_DOWN_LEFT);
	}
	else if (joy1Btn(BTN_HOOK_UP))
	{
		hook(HOOK_UP_RIGHT,HOOK_UP_LEFT);
	}

	if (joy1Btn(BTN_DOOR_OPEN))
	{
		boxdoor(DOOR_OPEN);
	}
	else if (joy1Btn(BTN_DOOR_CLOSE))
	{
		boxdoor(DOOR_CLOSE);
	}

	if(joy1Btn(BTN_LIFT_UP))
	{
		manual_lift(MOTOR_MAX);
	}
	else if(joy1Btn(BTN_LIFT_DOWN))
	{
		manual_lift(-MOTOR_MAX);
	}
	else
	{
		manual_lift(MOTOR_STOP);
	}

	drivetrain();
	doorslide();
}

// scales a -128 to 128 range to -100 to 100 using integer math
// allows using full range of joystick
// it is important to multiply before dividing to avoid
// losing numerical precision
int joystick_scale(int val)
{
	return val * 100 / 128;
}

void drivetrain()
{
	int left = 0;
	int right = 0;
	int scaled;

	if(abs(joystick.joy1_x2) > joystick_threshold)
	{
		scaled = joystick_scale(joystick.joy1_x2);
		left = right = scaled;
	}

	if(abs(joystick.joy1_y1) > joystick_threshold)
	{
		scaled = joystick_scale(joystick.joy1_y1);
		left += scaled;
		right -= scaled;
	}

	// bound to -100 to 100
	if (left > 100) left = 100;
	if (left < -100) left = 100;
	if (right > 100) right = 100;
	if (right < -100) right = 100;


	motor[leftdrive1] = left;
	motor[leftdrive2] = left;
	motor[rightdrive1] = right;
	motor[rightdrive2] = right;
}
void sweep(int power)
{
	motor[intakesweep] = power;

}

void manual_lift(int power)
{
	motor[lift] = power;
	//motor[rightLift] = power;
}

void hook(int position1, int position2)
{
	servoTarget[hook1] = position1;
	servoTarget[hook2] = position2;
}

void boxdoor(int position)
{
	servoTarget[door] = position;
}

void doorslide()
{
	getJoystickSettings (joystick);

	//if (joy1_TopHat == POV_LEFT)
	//{
	//	manual_lift_mode = 1;
	//	PlayTone(1000,1000);
	//	StopTask(Lift_Task);
 // }
 // else if (joy1_TopHat == POV_RIGHT)
 // {
 // 	manual_lift_mode = 0;
 // 	PlayTone(500,1000);
 // 	StartTask(Lift_Task);
 // }
	//else if (manual_lift_mode && (joy1_TopHat == POV_UP))
	//{
	//	motor[lift] = 100;
	//}
	//else if (manual_lift_mode && (joy1_TopHat == POV_DOWN))
	//{
	//	motor[lift] = -100;
	//}
	//else if (manual_lift_mode)
	//{
	//  motor[lift]= 0;
	//}

	if (joy1Btn(BTN_LIFT_UP))
	{
	//	motor[lift] = 100;
	}
	else if (joy1Btn(BTN_LIFT_DOWN) && (SensorValue[endstop] < ENDSTOP_THRES))
	{
	 //  motor[lift] = -100;

	 }

	 else
	 {
	   //motor[lift] = 0;
	 }
}

#define KPn 1 // Constant of Porportionality Numerator
#define KPd 5 // Denumerator
#define ERROR_MAX (MOTOR_MAX * KPd / KPn) // Above this amount of error,
                                          // output to motor will be 100% power

task Lift_Task()
{
	int curr;
	int error;
	int output;
	bool endstop_trig;
	//nMotorEncoder[lift] = LIFT_BOTTOM;
	lift_target = LIFT_BOTTOM;

	while(1)
	{
		endstop_trig = SensorValue[endstop] > ENDSTOP_THRES;
	  //if (endstop_trig) nMotorEncoder[lift] = 0;

	  //if ((lift_target == LIFT_BOTTOM) && !endstop_trig) nMotorEncoder[lift] += 1;

	  //curr = nMotorEncoder[lift];
	  error = lift_target - curr;

	  // bound the error to avoid integer overflow when multiplying it by Kp later
	  if (error > ERROR_MAX) error = ERROR_MAX;
	  if (error < -ERROR_MAX) error = -ERROR_MAX;

	  output = error * KPn / KPd;
	  //motor[lift] = output;


		wait1Msec(10);
	}
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  //StartTask(Lift_Task);

  initializeRobot();

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
  	control ();
    wait1Msec(10);



	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////
	  ////                                                   ////
	  ////      Add your robot specific tele-op code here.   ////
	  ////                                                   ////
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////

    // Insert code to have servos and motors respond to joystick and button values.

    // Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
    // You may be able to find "snippets" of code that are similar to the functions that you want to
    // perform.
  }
}
