#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          clamp,         tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     leftLift,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     intakeSweep,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    intakeDoor,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    releaseDoor,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    clampServo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define BTN_TRIG_LT 7
#define BTN_SWEEP_OUT BTN_TRIG_LT
#define BTN_TRIG_RT 8
#define BTN_SWEEP_IN BTN_TRIG_RT
#define BTN_FACE_X 1
#define BTN_RELEASE_DOOR_OPEN BTN_FACE_X
#define BTN_TRIG_LB 5
#define BTN_INTAKE_DOOR_CLOSED BTN_TRIG_LB
#define BTN_TRIG_RB 6
#define BTN_INTAKE_DOOR_OPEN BTN_TRIG_RB
#define BTN_FACE_Y 4
#define BTN_LIFT_UP BTN_FACE_Y
#define BTN_FACE_A 2
#define BTN_LIFT_DOWN BTN_FACE_A

#define BTN_FACE_B 3
#define BTN_CLAMP BTN_FACE_B
#define BTN_CLAMP_UP 9
#define BTN_CLAMP_DOWN 10

#define MOTOR_STOP 0
#define MOTOR_HALF 50
#define MOTOR_MAX 100

#define INTAKE_OPEN 170
#define INTAKE_CLOSED 10

#define RELEASE_OPEN 40
#define RELEASE_CLOSED 215

#define CLAMP_DOWN 40
#define CLAMP_UP 100

int joystick_threshold = 5; //used to prevent small inputs from affecting motors
int lift_encoder = 1000; //used to lift box to a set postion
int lift_is_up = 0; //used to see which position the lift is in
int release_door_is_open = 0;

int clamp_encoder = 45;
int clamp_is_open = 1;
//int clamp_power;

int lift_power; //use to determine the direction of the lift

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void control();
void sweep(int power);
void intake_door(int position);
void release_door(int position);
void clamp_base(int position);
void lift();
void manual_lift(int power);
void drivetrain();
//task clamp_macro();

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	nMotorEncoder[leftDrive] = 0; //zeros the drive motor encoders
	nMotorEncoder[rightDrive] = 0;

	nMotorEncoder[leftLift] = 0; //zeros the lift motor encoders
	//nMotorEncoder[rightLift] = 0;
	servoChangeRate[releaseDoor] = 2;
	servoTarget[intakeDoor] = INTAKE_OPEN; //set the intake door an open position
	servoTarget[releaseDoor] = RELEASE_CLOSED; //set the release door to a closed position

	servoTarget[clampServo] = CLAMP_UP;


  return;
}

void control() //main function to control all robot functionality
{
	getJoystickSettings(joystick);

	if(joy1Btn(BTN_SWEEP_IN))
	{
		sweep(-MOTOR_MAX);
	}
	else if(joy1Btn(BTN_SWEEP_OUT))
	{
		sweep(MOTOR_MAX);
	}
	else
	{
		sweep(MOTOR_STOP);
	}

	if(joy1Btn(BTN_INTAKE_DOOR_OPEN))
	{
		intake_door(INTAKE_OPEN);
	}
	else if(joy1Btn(BTN_INTAKE_DOOR_CLOSED))
	{
		intake_door(INTAKE_CLOSED);
	}

	if(joy1Btn(BTN_RELEASE_DOOR_OPEN) && !release_door_is_open)
	{
		release_door(RELEASE_OPEN);
		wait1Msec(500);
		release_door_is_open = 1;
	}
	else if(joy1Btn(BTN_RELEASE_DOOR_OPEN) && release_door_is_open)
	{
		release_door(RELEASE_CLOSED);
		wait1Msec(500);
		release_door_is_open = 0;
	}

	if(joy1Btn(BTN_CLAMP_UP))
	{
		clamp_base(CLAMP_UP);
	}
	else if(joy1Btn(BTN_CLAMP_DOWN))
	{
		clamp_base(CLAMP_DOWN);
	}

	//else
	//{
	//	clamp_base(MOTOR_STOP);
	//}

	//if(joy1Btn(BTN_CLAMP_OPEN))
	//{
	//	clamp_base(MOTOR_MAX);
	//	clamp_is_open = 1;
	//}
	//else if(joy1Btn(BTN_CLAMP_CLOSE))
	//{
	//	clamp_base(-MOTOR_MAX);
	//	clamp_is_open = 0;
	//}
	//else
	//{
	//	if (clamp_is_open)
	//		clamp_base(MOTOR_STOP);
	//  else
	//  	clamp_base(MOTOR_HALF);
	//}

	//if(joy1Btn(BTN_CLAMP) && clamp_is_open)
	//{
	//	clamp_base(-MOTOR_MAX);
	//	clamp_is_open = 0;
	//}
	//else if(joy1Btn(BTN_CLAMP) && !clamp_is_open)
	//{
	//	clamp_base(MOTOR_MAX);
	//	clamp_is_open = 1;
	//}

	//if(joy1Btn(BTN_CLAMP_OPEN) && !clamp_is_open)
	//{
	//	clamp_power = -MOTOR_MAX;
	//	StartTask(clamp_macro);
	//	clamp_is_open = 1;
	//}
	//else if(joy1Btn(BTN_CLAMP_CLOSE) && clamp_is_open)
	//{
	//	clamp_power = MOTOR_MAX;
	//	StartTask(clamp_macro);
	//	clamp_is_open = 0;
	//}

	if(joy1Btn(BTN_LIFT_UP))
	{
		manual_lift(MOTOR_MAX);
	}
	else if(joy1Btn(BTN_LIFT_DOWN))
	{
		manual_lift(-MOTOR_MAX);
	}
	else
	{
		manual_lift(MOTOR_STOP);
	}

	drivetrain();
}

void sweep(int power)	//Function that will allow the user to control the Sweeper to suck or exhaust blocks.
{												// Power is a variable used to control the speed the motor sweeps at as controlled in task main().
	motor[intakeSweep] = power;
}

void intake_door(int position) //operates the intake door
{
	servoTarget[intakeDoor] = position;
}

void release_door(int position) //operates the release door
{
	servoTarget[releaseDoor] = position;
}


void clamp_base(int position)
{
	servoTarget[clampServo] =	position;

	 // bFloatDuringInactiveMotorPWM = false;
		//motor[clamp] = clamp_power;

		//nMotorEncoderTarget[clamp] = clamp_encoder;
		//motor[clamp] = clamp_power;
		//while(nMotorRunState[clamp] != runStateIdle)
		//{

		//}
		//motor[clamp] = MOTOR_STOP;
}

void lift()
{
	nMotorEncoderTarget[leftLift] = lift_encoder;
	motor[leftLift] = lift_power;
	//motor[rightLift] = lift_power;
	while(nMotorRunState[leftLift] != runStateIdle)
	{

	}
	motor[leftLift] = MOTOR_STOP;
	//motor[rightLift] = MOTOR_STOP;
	if(!lift_is_up)
	{
		intake_door(INTAKE_OPEN);
	}
}

void manual_lift(int power)
{
	motor[leftLift] = power;
	//motor[rightLift] = power;
}

void drivetrain() //operates the drivetrain
{
	if(abs(joystick.joy1_x2) > joystick_threshold)
	{
		motor[leftDrive] = joystick.joy1_x2;
		motor[rightDrive] = -joystick.joy1_x2;
	}
	else if(abs(joystick.joy1_y1) > joystick_threshold)
	{
		motor[leftDrive] = joystick.joy1_y1;
		motor[rightDrive] = joystick.joy1_y1;
	}
	else
	{
		motor[leftDrive] = MOTOR_STOP;
		motor[rightDrive] = MOTOR_STOP;
	}
}

//task clamp_macro()
//{
//		//clamp_base();
//}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////
	  ////                                                   ////
	  ////      Add your robot specific tele-op code here.   ////
	  ////                                                   ////
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////

    // Insert code to have servos and motors respond to joystick and button values.

    // Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
    // You may be able to find "snippets" of code that are similar to the functions that you want to
    // perform.

  	control();
  }
}
