#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     sensorSignal,   sensorLightActive)
#pragma config(Motor,  motorA,          motorLiftLeft, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorLiftRight, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorSweep,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servoDoor,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servoFlag,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DRIVE_FORWARD_ENCODER_COUNT 5500
#define DUMP_POSITION 125
#define DOOR_CLOSE_POSITION 0
#define DOOR_GROUND_LEVEL_OPEN 82
#define LIFT_ENCODER_COUNT 2700
#define NXT_MOTOR_MAX 100
#define NXT_MOTOR_STOP 0
#define DC_MOTOR_MAX 100
#define DC_MOTOR_STOP 0

int lift_encoder = LIFT_ENCODER_COUNT;
int drivepower = DC_MOTOR_MAX;

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an Tetrix robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void drive(int drive_encoder_left, int drive_encoder_right);
void lift(int liftpower);
void door(int position);

void initializeRobot()
{
  // Place code here to initialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	nMotorEncoder[motorLeft] = 0;
	nMotorEncoder[motorRight] = 0;
	servoTarget[servoDoor] = DOOR_GROUND_LEVEL_OPEN; //Set the servo door into the ground level open position

  return;
}

void drive(int drive_encoder_left, int drive_encoder_right)
{
	nMotorEncoderTarget[motorLeft] = drive_encoder_left;
	nMotorEncoderTarget[motorRight] = drive_encoder_right;
	motor[motorLeft] = -drivepower;
	motor[motorRight] = -drivepower;
	while((nMotorRunState[motorLeft] != runStateIdle) && (nMotorRunState[motorRight] != runStateIdle))
	{

	}
	motor[motorLeft] = DC_MOTOR_STOP;
	motor[motorRight] = DC_MOTOR_STOP;
}

void lift(int liftpower)
{
	nMotorEncoderTarget[motorLiftLeft] = lift_encoder;
	motor[motorLiftLeft] = liftpower;
	while(nMotorRunState[motorLiftLeft] != runStateIdle)
	{

	}
	motor[motorLiftLeft] = NXT_MOTOR_STOP;
}

void door(int position)	//Function will allow user to close door at 0* on the servo.
{
	servoTarget[servoDoor] = position;
	if(position == DOOR_CLOSE_POSITION)
	{
		SensorType[sensorSignal] = sensorLightInactive;
	}
	else if(position == DOOR_GROUND_LEVEL_OPEN || position == DUMP_POSITION)
	{
		SensorType[sensorSignal] = sensorLightActive;
	}
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  drive(DRIVE_FORWARD_ENCODER_COUNT, DRIVE_FORWARD_ENCODER_COUNT);

  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////
  ////                                                   ////
  ////    Add your robot specific autonomous code here.  ////
  ////                                                   ////
  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////

  while (true)
  {

  }
}
