 #pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S3,     sensorSignal,   sensorLightActive)
#pragma config(Motor,  motorA,          motorLiftLeft, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorLiftRight, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorSweep,    tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servoDoor,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servoFlag,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define BTN_TRIG_LT 7
#define BTN_SWEEP_IN BTN_TRIG_LT
#define BTN_TRIG_RT 8
#define BTN_SWEEP_OUT BTN_TRIG_RT
#define BTN_FACE_X 1
#define BTN_DOOR_DUMP BTN_FACE_X
#define BTN_TRIG_LB 5
#define BTN_DOOR_CLOSE BTN_TRIG_LB
#define BTN_TRIG_RB 6
#define BTN_DOOR_OPEN BTN_TRIG_RB
#define BTN_FACE_Y 4
#define BTN_LIFT_UP BTN_FACE_Y
#define BTN_FACE_A 2
#define BTN_LIFT_DOWN BTN_FACE_A
#define DUMP_POSITION 125
#define DOOR_CLOSE_POSITION 0
#define DOOR_GROUND_LEVEL_OPEN 90
#define LIFT_ENCODER_COUNT 2700
#define NXT_MOTOR_MAX 100
#define NXT_MOTOR_STOP 0
#define DC_MOTOR_MAX 100
#define DC_MOTOR_STOP 0
#define DRIVETRAIN_THRESHOLD 20

int lift_is_up = 0; //Used to keep lifting when already lifted or bring down when already bring down.
int liftpower;
int encoder = LIFT_ENCODER_COUNT;
int threshold = DRIVETRAIN_THRESHOLD;

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void control();
void sweep(int power);
void door(int position);
void lift();
void drivetrain();
task lift_macro();

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	servoTarget[servoDoor] = DOOR_GROUND_LEVEL_OPEN; //Set the servo door into the ground level open position
	nSyncedMotors = synchAB; //Synchroizes left and right lift motors
	nMotorEncoder[motorLiftLeft] = 0; //Sets the current position of the left lift motor encoder to zero

  return;
}

void control()
{
	getJoystickSettings(joystick);

	if(joy1Btn(BTN_SWEEP_IN))
	{
		sweep(NXT_MOTOR_MAX);
	}
	else if(joy1Btn(BTN_SWEEP_OUT))
	{
		sweep(-NXT_MOTOR_MAX);
	}
	else
	{
		sweep(NXT_MOTOR_STOP);
	}

	if(joy1Btn(BTN_DOOR_OPEN))
	{
		door(DOOR_GROUND_LEVEL_OPEN);
	}
	else if(joy1Btn(BTN_DOOR_CLOSE))
	{
		door(DOOR_CLOSE_POSITION);
	}
	else if(joy1Btn(BTN_DOOR_DUMP) && lift_is_up)
	{
		door(DUMP_POSITION);
	}

	if(joy1Btn(BTN_LIFT_UP) && !lift_is_up)
	{
		door(DOOR_CLOSE_POSITION);
		liftpower = -NXT_MOTOR_MAX;
		StartTask(lift_macro);
		lift_is_up = 1;
	}
	else if(joy1Btn(BTN_LIFT_DOWN) && lift_is_up)
	{
		door(DOOR_CLOSE_POSITION);
		liftpower = NXT_MOTOR_MAX;
		StartTask(lift_macro);
		lift_is_up = 0;
	}

	drivetrain();
}



void sweep(int power)	//Function that will allow the user to control the Sweeper to suck or exhaust blocks.
{												// Power is a variable used to control the speed the motor sweeps at as controlled in task main().
	motor[motorSweep] = power;
}

void door(int position)	//Function will allow user to close door at 0* on the servo.
{
	servoTarget[servoDoor] = position;
	if(position == DOOR_CLOSE_POSITION)
	{
		SensorType[sensorSignal] = sensorLightInactive;
	}
	else if(position == DOOR_GROUND_LEVEL_OPEN || position == DUMP_POSITION)
	{
		SensorType[sensorSignal] = sensorLightActive;
	}
}

void lift()
{
	nMotorEncoderTarget[motorLiftLeft] = encoder;
	motor[motorLiftLeft] = liftpower;
	while(nMotorRunState[motorLiftLeft] != runStateIdle)
	{

	}
	motor[motorLiftLeft] = NXT_MOTOR_STOP;
	if(!lift_is_up)
	{
		door(DOOR_GROUND_LEVEL_OPEN);
	}
}

void drivetrain()
{
	if(abs(joystick.joy1_x2) > threshold)
	{
		motor[motorLeft] = -joystick.joy1_x2;
		motor[motorRight] = joystick.joy1_x2;
	}
	else if(abs(joystick.joy1_y1) > threshold)
	{
		motor[motorLeft] = joystick.joy1_y1;
		motor[motorRight] = joystick.joy1_y1;
	}
	else
	{
		motor[motorLeft] = DC_MOTOR_STOP;
		motor[motorRight] = DC_MOTOR_STOP;
	}
}

task lift_macro()
{
	lift();
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  //waitForStart();   // wait for start of tele-op phase

  while (true)
  {
  	control();

	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////
	  ////                                                   ////
	  ////      Add your robot specific tele-op code here.   ////
	  ////                                                   ////
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////

    // Insert code to have servos and motors respond to joystick and button values.

    // Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
    // You may be able to find "snippets" of code that are similar to the functions that you want to
    // perform.
  }
}
