#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,            tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servoTest,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		servoTarget[servoTest] = 0;
		wait1Msec(2000);
		servoTarget[servoTest] = 180;
		wait1Msec(2000);
		servoTarget[servoTest] = 0;
		wait1Msec(2000);
		servoTarget[servoTest] = 180;
		wait1Msec(2000);
		servoTarget[servoTest] = 0;
		wait1Msec(2000);
		servoTarget[servoTest] = 200;
		wait1Msec(2000);
}
